---
title: "Analysis of STEAM uising pattern"
output: html_notebook
---

# Summary 

- STEAM is not a platform only for collecting games. 
- DOTA2 occupies around 28% of total playtime of STEAM users. 
- "Counter-strike Globl Offensive" has a unique 'long tail' in the distribution of playing time. 


# STEAM: only for collectors? 

Sometimes, people says that, "STEAM is not platform for playing games, but only for collecting." This means that they buys games, but do not play most of the game purchased. I have some collection in STEAM that has not been played for a single time. I wonder this is really trend among STEAM users? 

I found a related data set in [Keggle](https://www.kaggle.com/tamber/steam-video-games). The data set may not be strongly reliable because details on data generation is not provided. For example, the time range for data set is not speficifed. 
the data set is the best one that can be collected by now, 



```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
